on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Install Dagger
      uses: dagger/dagger-for-github@v4
      with:
        install-only: true
    -
      name: Show Dagger version
      run: dagger-cue version
